server:
  port: 8100
spring:
  application:
    name: book-service
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 4415eeb428d807a00882ab7ca072cc58b36b5ba0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?userTimezone=true&serverTimezone=UTC
    username: root
    password: 1010
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
<<<<<<< HEAD
    password: 1010
=======
    password: 1010

=======
>>>>>>> 7187068f8e5f1d0b3c9f751de4f645058c598c02
>>>>>>> 4415eeb428d807a00882ab7ca072cc58b36b5ba0
